name: rentx_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  shelf_modular: ^1.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  mongo_dart: ^0.7.4
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.1

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
